/**
 * Hostaway amenity name → CHECK24 Property amenity enum.
 * Only values accepted by Supply API v2 Amenity.name are emitted.
 */
const VALID_AMENITIES = new Set<string>([
  'key_collection',
  'registration_number',
  'bed_linen',
  'closet',
  'pillow_without_feathers',
  'pillow_with_feathers',
  'hypoallergenic_pillow',
  'extra_bed',
  'mosquito_net',
  'washing_machine',
  'iron_ironing_board',
  'laundry_rack',
  'clothes_dryer',
  'bed_double',
  'bed_sofa',
  'bed_single',
  'bed_bunk',
  'bed_futon',
  'bed_king',
  'bed_queen',
  'shower',
  'bathtub',
  'bathtub_shower',
  'additional_toilet',
  'bidet',
  'towels',
  'hairdryer',
  'toilet_paper',
  'bathrobe',
  'kitchen',
  'refrigerator',
  'fridge_freezer_combination',
  'oven',
  'stove',
  'dishwasher',
  'microwave',
  'coffee_machine',
  'water_kettle',
  'toaster',
  'dining_area',
  'wine_glasses',
  'kitchenware',
  'cutlery',
  'dishes',
  'dish_towels',
  'espresso_machine',
  'cooking_plate',
  'automatic_coffee_machine',
  'freezer',
  'sofa',
  'desk',
  'fireplace',
  'internet_wifi',
  'tv',
  'dvd_player',
  'streaming_services',
  'gaming_console',
  'balcony',
  'terrace',
  'garden_furniture',
  'garden',
  'outdoor_dining_area',
  'sun_chairs',
  'outside_fireplace',
  'sunshades',
  'veranda',
  'minibar',
  'grill',
  'breakfast_service',
  'heater',
  'air_conditioner',
  'elevator',
  'fan',
  'vacuum_cleaner',
  'smoke_detector',
  'fire_extinguisher',
  'safe',
  'carbon_monoxide_detector',
  'non_smoking_accommodation',
  'cleaning_supplies',
  'smoking_section',
  'allergy_friendly',
  'concierge',
  'room_cleaning',
  'parking',
  'private_entrance_accommodation',
  'electrical_vehicle_charging',
  'pool',
  'private_pool',
  'pool_beach_towels',
  'whirlpool',
  'sauna',
  'spa',
  'massage',
  'steam_bath',
  'private_whirlpool',
  'whirlpool_bathtub',
  'thermal_baths',
  'private_sauna',
  'beach_chairs',
  'boat_dock',
  'pets_allowed',
  'child_friendly',
  'child_bed',
  'child_high_chair',
  'playground',
  'child_media',
  'child_cutlery',
  'baby_monitor',
  'baby_changing_mat',
  'baby_bath',
  'childcare',
  'playarea',
  'children_pool',
  'non_swimmers_area',
  'watertoys',
  'toddler_equipment',
  'child_program',
  'toys',
  'childrens_room',
  'baby_equipment',
  'shallow_end_pool',
  'shared_kitchen',
  'shared_bathroom',
  'shared_accommodation',
  'shared_garden',
  'washing_machine_shared',
  'dryer_shared',
  'shareduse_pool',
  'shareduse_sauna',
  'shareduse_jacuzzi',
  'shareduse_steam_bath',
  'wheelchair_accessible',
  'higher_toilet',
  'low_sink',
  'barrier_free_bathroom',
  'direct_ski_access',
  'direct_access_beach_or_lake',
  'garden_view',
  'mountain_view',
  'quiet_street_view',
  'city_view',
  'sea_view',
  'courtyard_view',
  'sightseeing_view',
  'pool_view',
  'lake_view',
  'river_view',
  'panorama_view',
  'partial_sea_view',
  'partial_lake_view',
  'harbor_view',
  'house_with_water_view',
  'partial_water_view',
  'fitness',
  'fishing',
  'table_tennis',
  'minigolf',
  'billard',
  'tennis_court',
  'snorkeling',
  'skiing_snowboarding',
  'riding',
  'bowling',
  'darts',
  'hiking',
  'squash',
  'windsurfing',
  'canoe',
  'diving',
  'bike_riding',
  'bikes',
]);

const AMENITY_ALIASES: Record<string, string> = {
  wifi: 'internet_wifi',
  wireless: 'internet_wifi',
  internet: 'internet_wifi',
  'wireless internet': 'internet_wifi',
  washer: 'washing_machine',
  washingmachine: 'washing_machine',
  'washing machine': 'washing_machine',
  dryer: 'clothes_dryer',
  'clothes dryer': 'clothes_dryer',
  dishwasher: 'dishwasher',
  microwave: 'microwave',
  refrigerator: 'refrigerator',
  fridge: 'refrigerator',
  freezer: 'freezer',
  oven: 'oven',
  stove: 'stove',
  coffee: 'coffee_machine',
  coffeemaker: 'coffee_machine',
  'coffee maker': 'coffee_machine',
  'coffee machine': 'coffee_machine',
  tv: 'tv',
  television: 'tv',
  airconditioning: 'air_conditioner',
  'air conditioning': 'air_conditioner',
  ac: 'air_conditioner',
  heating: 'heater',
  fireplace: 'fireplace',
  balcony: 'balcony',
  terrace: 'terrace',
  patio: 'terrace',
  garden: 'garden',
  parking: 'parking',
  'free parking': 'parking',
  'free parking on premises': 'parking',
  garage: 'parking',
  elevator: 'elevator',
  lift: 'elevator',
  pool: 'pool',
  swimmingpool: 'pool',
  'swimming pool': 'pool',
  hottub: 'whirlpool',
  'hot tub': 'whirlpool',
  jacuzzi: 'whirlpool',
  sauna: 'sauna',
  gym: 'fitness',
  fitness: 'fitness',
  petsallowed: 'pets_allowed',
  'pets allowed': 'pets_allowed',
  pets: 'pets_allowed',
  crib: 'child_bed',
  babycot: 'child_bed',
  'baby cot': 'child_bed',
  highchair: 'child_high_chair',
  'high chair': 'child_high_chair',
  hairdryer: 'hairdryer',
  'hair dryer': 'hairdryer',
  iron: 'iron_ironing_board',
  kettle: 'water_kettle',
  toaster: 'toaster',
  mosquitonet: 'mosquito_net',
  'mosquito net': 'mosquito_net',
  bbq: 'grill',
  barbecue: 'grill',
  grill: 'grill',
  kitchen: 'kitchen',
  towels: 'towels',
  bathtub: 'bathtub',
  shower: 'shower',
  'smoke detector': 'smoke_detector',
  'carbon monoxide detector': 'carbon_monoxide_detector',
  'fire extinguisher': 'fire_extinguisher',
  'wheelchair accessible': 'wheelchair_accessible',
};

export function mapHostawayAmenityName(
  amenityName: string | null | undefined,
): string | null {
  if (!amenityName) return null;
  const key = amenityName.trim().toLowerCase().replace(/[_-]+/g, ' ');
  const mapped =
    AMENITY_ALIASES[key] ??
    AMENITY_ALIASES[key.replace(/\s+/g, '')] ??
    null;
  if (!mapped) return null;
  return VALID_AMENITIES.has(mapped) ? mapped : null;
}
